/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao2;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import modelo.dao.FabricanteDao;
import modelo.dao.ModeloDao;
import modelo.entidade.Fabricante;
import modelo.entidade.Modelo;

/**
 *
 * @author lucas
 */
public class TelaListModelo extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaListModelo
     */
    public TelaListModelo() {
        initComponents();
        preencherTabelaModelo();
        preencherComboFabricante(jcfabricante);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTcodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTdescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcfabricante = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jTmodelo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btBuscarModelo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTModel = new javax.swing.JTable();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Listar Modelo");

        jLabel2.setText("Codigo");

        jLabel3.setText("Descrição");

        jLabel4.setText("Fabricante");

        jcfabricante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha..." }));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTmodelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTmodeloKeyReleased(evt);
            }
        });

        jLabel1.setText("Informe Modelo");

        btBuscarModelo.setText("Buscar");
        btBuscarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarModeloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btBuscarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btBuscarModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jTmodelo))
                .addContainerGap())
        );

        jTModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Modelo", "Fabricante"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTModel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTModelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTModel);
        if (jTModel.getColumnModel().getColumnCount() > 0) {
            jTModel.getColumnModel().getColumn(0).setResizable(false);
            jTModel.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTModel.getColumnModel().getColumn(1).setResizable(false);
            jTModel.getColumnModel().getColumn(1).setPreferredWidth(240);
            jTModel.getColumnModel().getColumn(2).setResizable(false);
            jTModel.getColumnModel().getColumn(2).setPreferredWidth(240);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTcodigo)
                    .addComponent(jTdescricao)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jcfabricante, 0, 598, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jcfabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        btAlterar.setText("Alterar");
        btAlterar.setEnabled(false);

        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btBuscarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarModeloActionPerformed
        preencherTabelaModelo();
    }//GEN-LAST:event_btBuscarModeloActionPerformed

    private void jTmodeloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTmodeloKeyReleased
        preencherTabelaModelo();// TODO add your handling code here:
    }//GEN-LAST:event_jTmodeloKeyReleased

    private void jTModelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTModelMouseClicked
        buscarModelo();// TODO add your handling code here:
    }//GEN-LAST:event_jTModelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btBuscarModelo;
    private javax.swing.JButton btExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTModel;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JTextField jTdescricao;
    private javax.swing.JTextField jTmodelo;
    private javax.swing.JComboBox<String> jcfabricante;
    // End of variables declaration//GEN-END:variables

    private void preencherTabelaModelo() {

        limpartabela();

        String des = jTdescricao.getText();
        List<Modelo> lista;
        try {
            lista = new ModeloDao().ListarTodos(des);
            DefaultTableModel tabela = (DefaultTableModel) jTModel.getModel();

            for (Modelo m : lista) {
                tabela.addRow(new Object[]{m.getmoid(), m.getmodesc(), m.getfabricante().getfanome()});

            }

        } catch (SQLException ex) {
            Logger.getLogger(TelaListModelo.class.getName()).log(Level.SEVERE, null, ex);

        }

    }

    private void limpartabela() {

        while (jTModel.getModel().getRowCount() > 0) {
            ((DefaultTableModel) jTModel.getModel()).removeRow(0);
        }

    }//fim

    public void preencherComboFabricante(JComboBox combo) {
        FabricanteDao fdao = new FabricanteDao();

        try {
            List<Fabricante> lista = fdao.listarTodos();

            for (Fabricante fab : lista) {
                combo.addItem(fab);
            }
        } catch (SQLException ex) {

            System.out.println("Erro ao recuperar");
        }

    }

    private void buscarModelo() {
        int linha = jTModel.getSelectedRow();
        int codigo = Integer.parseInt(String.valueOf(jTModel.getValueAt(linha, 0)));

        try {

            Modelo modelo = new ModeloDao().buscar(codigo);
            jTcodigo.setText(String.valueOf(modelo.getmoid()));
            jTdescricao.setText(modelo.getmodesc());
            jcfabricante.getModel().setSelectedItem(modelo.getfabricante());
            btAlterar.setEnabled(true);

        } catch (SQLException ex) {
            Logger.getLogger(TelaListModelo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//fim

}
