/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import modelo.dao.FabricanteDao;
import modelo.dao.ModeloDao;
import modelo.entidade.Fabricante;
import modelo.entidade.Modelo;

/**
 *
 * @author lucas
 */
public class TelaCadModelo extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadModelo
     */
    public TelaCadModelo() {
        initComponents();
        preencherComboFabricante(jcfabricante);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtdesc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcfabricante = new javax.swing.JComboBox<>();
        btsalvar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Modelo");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setToolTipText("Cadastro de Modelo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Descrição");

        jtxtdesc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Fabricante");

        jcfabricante.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jcfabricante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha..." }));

        btsalvar.setBackground(new java.awt.Color(51, 153, 0));
        btsalvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btsalvar.setText("Salvar");
        btsalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtdesc)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jcfabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(btsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcfabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed

        if (jtxtdesc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "preencha a descrição do modelo");
            jtxtdesc.requestFocus();
        } else if (jcfabricante.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Escolha o fabricante");
        } else {
            cadastrar();
        }

    }//GEN-LAST:event_btsalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btsalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jcfabricante;
    private javax.swing.JTextField jtxtdesc;
    // End of variables declaration//GEN-END:variables

    private void cadastrar() {

        ModeloDao mdao = new ModeloDao();
        Modelo mod = new Modelo();

        mod.setmodesc(jtxtdesc.getText());

        Fabricante fab = (Fabricante) jcfabricante.getSelectedItem();

        mod.setfabricante(fab);

        jtxtdesc.setText("");
        jcfabricante.setSelectedIndex(0);
        jtxtdesc.requestFocus();

        try {
            mdao.cadastrar(mod);

            System.out.println("Salvo com Sucesso");
        } catch (SQLException ex) {
            System.out.println("Não salvou");;
        }

    }

    public void preencherComboFabricante(JComboBox combo) {
        FabricanteDao fdao = new FabricanteDao();

        try {
            List<Fabricante> lista = fdao.listarTodos();

            for (Fabricante fab : lista) {
                combo.addItem(fab);
            }
        } catch (SQLException ex) {

            System.out.println("Erro ao recuperar");
        }

    }

}
