/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.sql.SQLException;
import modelo.dao.UsuarioDao;
import modelo.entidade.Usuario;

/**
 *
 * @author lucas
 */
public class VWPesqUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VWPesqUsuario
     */
    public VWPesqUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbBuscar = new javax.swing.JButton();
        jtcodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbexcluir = new javax.swing.JButton();
        jbeditar = new javax.swing.JButton();
        jbcancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlaviso = new javax.swing.JLabel();
        jtnome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtlogin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jpsenha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo:");

        jbexcluir.setText("Excluir");
        jbexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexcluirActionPerformed(evt);
            }
        });

        jbeditar.setText("Editar");
        jbeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeditarActionPerformed(evt);
            }
        });

        jbcancelar.setText("Cancelar");
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Pesquisa de Usuario");

        jlaviso.setForeground(new java.awt.Color(51, 51, 51));

        jLabel4.setText("Login:");

        jLabel5.setText("Senha:");

        jpsenha.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(jpsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbBuscar))))))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jbcancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbeditar)
                .addGap(18, 18, 18)
                .addComponent(jbexcluir)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlaviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jlaviso, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbeditar)
                    .addComponent(jbcancelar)
                    .addComponent(jbexcluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        jlaviso.setText("");
        int id;

        //Zona zona = new Zona();
        if ("".equals(jtcodigo.getText()) || jtcodigo.getText() == null) {
            jtnome.setText("");
            jlaviso.setForeground(Color.red);
            jlaviso.setText("*Por favor preencha o campo codigo");
            jtcodigo.requestFocus();

        } else {
            UsuarioDao usao = new UsuarioDao();
            id = (Integer.parseInt(jtcodigo.getText()));
            try {
                Usuario usuario = usao.Buscar(id);
                if (usuario.getUsid() != id || jtcodigo.getText() == null) {
                    System.out.println("*Usuario não cadastrado");
                    jlaviso.setForeground(Color.red);
                    jlaviso.setText("*Usuario não Cadastrado");
                } else {
                    //jtCodigo.setText(zona.getZoid());
                    jtnome.setText(usuario.getUsnome());
                    jtlogin.setText(usuario.getUslogin());
                    jtlogin.setText(usuario.getUssenha());

                }

            } catch (SQLException ex) {
                System.out.println("*Erro ao Buscar" + ex.getMessage());
                jlaviso.setForeground(Color.red);
                jlaviso.setText("*Erro ao Buscar" + ex.getMessage());
            }

        }

    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexcluirActionPerformed
        jlaviso.setText("");
        int id;
        //Zona zona = new Zona();
        UsuarioDao udao = new UsuarioDao();
        id = (Integer.parseInt(jtcodigo.getText()));
        //zona.setZoid(Integer.parseInt(jtcodigo.getText()));
        //zona.setZonome(jtnome.getText());

        try {
            udao.Excluir(id);
            System.out.println("*Usuario Excluido");
            jlaviso.setForeground(Color.green.darker());
            jlaviso.setText("*Usuario Excluido");
            jtnome.setText("");
            jtlogin.setText("");
            jtlogin.setText("");

        } catch (SQLException ex) {
            System.out.println("*Erro ao Excluir" + ex.getMessage());
            jlaviso.setForeground(Color.red);
            jlaviso.setText("*Erro ao Exluir" + ex.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_jbexcluirActionPerformed

    private void jbeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeditarActionPerformed
        jlaviso.setText("");
        //int id;
        Usuario usuario = new Usuario();
        UsuarioDao udao = new UsuarioDao();
        usuario.setUsid(Integer.parseInt(jtcodigo.getText()));
        usuario.setUsnome(jtnome.getText());
        usuario.setUslogin(jtlogin.getText());
        usuario.setUssenha(jpsenha.getText());

        try {
            udao.Alterar(usuario);
            System.out.println("*Usuario Alterado");
            jlaviso.setForeground(Color.green.darker());
            jlaviso.setText("*Usuario Alterado");
            jtnome.setText("");
            jtlogin.setText("");
            jtlogin.setText("");

        } catch (SQLException ex) {
            System.out.println("*Erro ao Alterar" + ex.getMessage());
            jlaviso.setForeground(Color.red);
            jlaviso.setText("*Erro ao Alterar" + ex.getMessage());
        }

        /*try {
            //Zona zona = zdao.Buscar(id);
            if(zona==null){
                System.out.println("Zona não cadastrada");
                jlaviso.setForeground(Color.red);
                jlaviso.setText("Zona não Cadastrada");
            }else{
                //jtCodigo.setText(zona.getZoid());
                jtnome.setText(zona.getZonome());

            }

        } catch (SQLException ex) {
            System.out.println("Erro ao Buscar" +ex.getMessage());
            jlaviso.setForeground(Color.red);
            jlaviso.setText("Erro ao Buscar" +ex.getMessage());
        }// TODO add your handling code here:*/
    }//GEN-LAST:event_jbeditarActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jbcancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VWPesqUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VWPesqUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VWPesqUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VWPesqUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VWPesqUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbcancelar;
    private javax.swing.JButton jbeditar;
    private javax.swing.JButton jbexcluir;
    private javax.swing.JLabel jlaviso;
    private javax.swing.JTextField jpsenha;
    private javax.swing.JTextField jtcodigo;
    private javax.swing.JTextField jtlogin;
    private javax.swing.JTextField jtnome;
    // End of variables declaration//GEN-END:variables
}
